# -*- coding: utf-8 -*-
"""
build_fx.py — 把 pricing.json 变成浏览器可读的 pricing.js

为什么需要这一步：
  landed 价格公式（汇率 + 菜鸟运费）以前在两处各写一遍 ——
  tpl_common.py（Python，生成所有页面价格）和 index.html（首页计算器内联 JS）。
  改汇率时只改一处，页面上就会出现互相矛盾的数字，而 JSON-LD 里的 price
  与页面可见价格不一致会被 Google 判为结构化数据作弊。

现在 pricing.json 是唯一真相源：
  - tpl_common.py 直接读它（Python 侧）
  - build_fx.py 生成 pricing.js（浏览器侧），index.html 用 window.STG_PRICING

用法: python3 build_fx.py
"""
import json
import os

APP = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(APP, 'pricing.json')
OUT = os.path.join(APP, 'pricing.js')

# pricing.json 缺失时的兜底值（与文件保持一致，防止仓库状态异常导致全站崩溃）
DEFAULTS = {
    'cny_to_usd': 7.15,
    'cainiao_base_cny': 68.0,
    'cainiao_per_kg_cny': 45.6,
    'cainiao_free_kg': 0.5,
    'local_currency': {},
}


def load():
    if os.path.exists(SRC):
        try:
            with open(SRC, encoding='utf-8') as f:
                d = json.load(f)
            # 去掉下划线开头的注释字段
            return {k: v for k, v in d.items() if not k.startswith('_')}
        except Exception as e:
            print('  ! pricing.json 解析失败，使用兜底值: %s' % e)
    return dict(DEFAULTS)


def main():
    d = load()
    body = json.dumps(d, ensure_ascii=False, indent=2)
    js = (
        '// pricing.js — GENERATED by build_fx.py from pricing.json. DO NOT EDIT.\n'
        '// Landed-price constants shared by the homepage calculator and every\n'
        '// generated page, so the numbers can never disagree.\n'
        '(function () {\n'
        '  window.STG_PRICING = %s;\n'
        '  window.cainiaoShipUSD = function (kg) {\n'
        '    var p = window.STG_PRICING;\n'
        '    var cny = kg <= p.cainiao_free_kg\n'
        '      ? p.cainiao_base_cny\n'
        '      : p.cainiao_base_cny + (kg - p.cainiao_free_kg) * p.cainiao_per_kg_cny;\n'
        '    return cny / p.cny_to_usd;\n'
        '  };\n'
        '})();\n' % body
    )
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write(js)
    print('✓ pricing.js (%d bytes, cny_to_usd=%s)' % (
        os.path.getsize(OUT), d.get('cny_to_usd')))


if __name__ == '__main__':
    main()
