// pricing.js — GENERATED by build_fx.py from pricing.json. DO NOT EDIT.
// Landed-price constants shared by the homepage calculator and every
// generated page, so the numbers can never disagree.
(function () {
  window.STG_PRICING = {
  "updated": "2026-09-02",
  "cny_to_usd": 7.15,
  "cainiao_base_cny": 68.0,
  "cainiao_per_kg_cny": 45.6,
  "cainiao_free_kg": 0.5,
  "local_currency": {
    "AE": {
      "cur": "AED",
      "rate": 3.6725,
      "duty": 0.05,
      "vat": 0.05
    },
    "SA": {
      "cur": "SAR",
      "rate": 3.75,
      "duty": 0.05,
      "vat": 0.15
    },
    "KW": {
      "cur": "KWD",
      "rate": 0.307,
      "duty": 0.05,
      "vat": 0.0
    },
    "QA": {
      "cur": "QAR",
      "rate": 3.64,
      "duty": 0.05,
      "vat": 0.0
    },
    "BH": {
      "cur": "BHD",
      "rate": 0.376,
      "duty": 0.05,
      "vat": 0.1
    },
    "OM": {
      "cur": "OMR",
      "rate": 0.385,
      "duty": 0.05,
      "vat": 0.05
    }
  }
};
  window.cainiaoShipUSD = function (kg) {
    var p = window.STG_PRICING;
    var cny = kg <= p.cainiao_free_kg
      ? p.cainiao_base_cny
      : p.cainiao_base_cny + (kg - p.cainiao_free_kg) * p.cainiao_per_kg_cny;
    return cny / p.cny_to_usd;
  };
})();
